### ISSUE TITLE
Update API utils and fix product ID or slug check in query resolver/function

### ISSUE THREAD

**Issue by mikemurray** [reactioncommerce/api-service-catalogs#3]
## Issue Description

A recent update to `api-utils` and ID decoding has caused an issue with how the `slugOrId` param was decoded, always reading the slug as an ID.

**Comment by rondlite** [comment]
this still fails for some products.
https://shop.demandcluster.com/en/product/ban01-6500-banana-maat-41-46---happy-socks
cause an error, namespace not valid.
when using the ID instead of the slug, I get the product and instant redirect to:
https://shop.demandcluster.com/en/product/ban01-6500-banana-maat-41-46---happy-socks/cmVhY3Rpb24vY2F0YWxvZ1Byb2R1Y3RWYXJpYW50OjM4NGE5MThhNzQ3MzViZjY1YWIxZWZmMzUyYjNhYTFkN2IzYTE5ZTI=

it is now happening on less products than before, but still fails sometimes.
